version : "3" #docker-compose的版本
services: #容器的集合

  php-fpm:
    image: php:7.3-fpm
    container_name: php-fpm
    privileged: true
    links:
      - "mysql"
    ports:
      - "9000:9000"
    volumes:
      - ./www:/var/www/html

  nginx:
    image: nginx:latest
    container_name: nginx
    privileged: true
    links:
      - "php-fpm"
    ports:
      - "80:80"
    volumes:
      - ./www/:/usr/share/nginx/html/
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/cert/:/etc/nginx/cert/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log/error.log:/var/log/nginx/error.log

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/my.cnf
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456


