version : "3.1" #docker-compose的版本
services: #容器的集合

  php-fpm:
    build: ./php
    container_name: php-fpm
    privileged: true
    links:
      - "mysql"
    ports:
      - "9000:9000"
    volumes:
      - ${SOURCE_DIR}:/www

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    privileged: true
    links:
      - "php-fpm"
    ports:
      - "${HTTP_HOST_HTTP}:80"
      - "${HTTP_HOST_HTTPS}:443"
    volumes:
      - ${SOURCE_DIR}:/www
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d
      - ${NGINX_CERT_DIR}:/etc/ssl
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf
      - ${NGINX_LOG_DIR}:/var/log/nginx

  mysql:
    image: mysql:latest
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
      - ${MYSQL_MY_CNF}:/etc/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}


